sudo: false
language: java
jdk:
- oraclejdk7
install: mvn -Dmaven.test.skip.exec=true clean install -q

script: mvn -Dmaven.test.skip.exec=true deploy -q -s settings.xml

deploy:
  secret_access_key:
    secure: eaqXT+uxinyZVa/5DorLbSQlNSXeeI3yMROBg8wPdyp7ycMXG3uodqpyhUt6gcwayJw2rtjekgzY++iLzHSlKPheTM7a9J+QEB+QvmR77+cSdQb/nG23iisIkMmkpOYrhacoK2PEOF1M38fhu/AEqN1kDGW6DFUC0eLokxqZSgE=
  access_key_id:
    secure: R4WKDzSs6lCV/Lmo+SV1BEI7X6jR8QK/mUrPT6qxm181ZvnUM+0/UHRAKUMKIsHadTBFuT+f7uEPu/8mVZl1CGQUKMOfJiKH7rDnxV+CHNMplYZDCRMLjBPQ1HHVncxgznQTCJ0AezWSxe80EvC2vD/Kg9ZSBN2//SQIM5Xre40=
  provider: s3
  bucket: peoplepattern-maven-repo
  skip_cleanup: true
  acl: authenticated_read
